### ISSUE TITLE
Limit resize events.

### ISSUE THREAD

**Issue by gjersvik** [johnmccutchan/game_loop#3]
Browser are overzealous in there fireing of resize events. IE for example send 2 event for every mouse move and one for height and one for width. I would like you to limit that to something sane like once every 50 ms or something. As it is something i have always done in the past wit resize events. My most common task is to resize the canvas element or some other DOM task that is way to slow for the browsers rapid firing of resize events.

**Comment by beatgammit** [comment]
This was fixed in 93e388f121059dfdf1f329b9dcb6403134d784e3, no?
